language: python
cache:
  - directories:
    - $HOME/.cache/pip

python:
  - 3.6

install:
  - python3 setup.py install
  - cd examples
  - pip install -r requirements.txt

script:
  - nbpipeline -d -i
