language: python
cache:
  - directories:
    - $HOME/.cache/pip

python:
  - 3.6
  - 3.7

install:
  - python3 setup.py install
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script:
  - cd examples
  - nbpipeline -d -i
  - cd ..
  - python3 -m pytest --cov=data_vault -v

after_success:
  - codecov

